// <auto-generated />
using System;
using Emlak_Asp_Net_Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Emlak_Asp_Net_Api.Migrations
{
    [DbContext(typeof(ApplicationDbContextApp))]
    partial class ApplicationDbContextAppModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Emlak_Asp_Net_Api.Models.tbl_ilanlar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("ekleyen_kullanici_Id")
                        .HasColumnType("int");

                    b.Property<string>("ilan_baslik")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ilan_detay")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ilan_fiyat")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("ilan_goruntuleme")
                        .HasColumnType("int");

                    b.Property<int>("ilan_kategori_Id")
                        .HasColumnType("int");

                    b.Property<string>("ilan_resim")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("ilan_turu_Id")
                        .HasColumnType("int");

                    b.Property<DateTime>("tarih")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("tbl_ilanlar");
                });

            modelBuilder.Entity("Emlak_Asp_Net_Api.Models.tbl_kategori_ara", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("ilan_Id")
                        .HasColumnType("int");

                    b.Property<int>("kategori_Id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("tbl_kategori_ara");
                });

            modelBuilder.Entity("Emlak_Asp_Net_Api.Models.tbl_kategoriler", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("kategori_adi")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("tbl_kategoriler");
                });

            modelBuilder.Entity("Emlak_Asp_Net_Api.Models.tbl_kullanicilar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ad")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("kullanici_adi")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("sifre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("yetki_Id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("tbl_kullanicilar");
                });

            modelBuilder.Entity("Emlak_Asp_Net_Api.Models.tbl_turler", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("tur_adi")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("tbl_turler");
                });
#pragma warning restore 612, 618
        }
    }
}
